### ISSUE TITLE
Is this on ansible-galaxy ?

### ISSUE THREAD

**Issue by Manas-kashyap** [atb00ker/ansible-raspi-debian-setup#1]

**Comment by atb00ker** [comment]
I assume most people would need to make changes in it before they use it, so no, if there is a need for it "as-is" then I'll add it! :smile:

**Comment by Manas-kashyap** [comment]
Oh okay, well in ansible-galaxy we can download it and make changes as required.

**Comment by atb00ker** [comment]
Ah,
I planned to push to ansible-galaxy today, but I realized that for repositories on galaxy, you need to either keep the role in top directory or use the collections directory structure, I don't plan to do this for two reasons:
1. This directory structure is more convenient for such a small repository, I don't want to change it.
2. I really don't see a situation where pulling from galaxy and making changes would be more convenient than using Git for the same.

Hence, I am closing this as `wontfix`, if you need it on galaxy, you'd need to fork and work on that.
Let me know if you need help with that.
